### PR TITLE
Fix add-all to show error when adding contact with no role

### LINKED ISSUE #302: Add-all in search mode does not raise error message when adding a contact with no role

### PR DESCRIPTION
**Pull request by cshao02**
Fixes #302 

Previously when adding contacts from search-mode using add-all command, when contact has no role, the result display does not say anything, in other words, it fails silently. 

This PR attempts to fix that by adding an error message when user tries to add contact with no role using add-all in search mode.

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -27,6 +27,9 @@ public class Messages {
     public static final String MESSAGE_USER_SEARCH_QUERY_ROLES = "Displaying search results for all contacts "
             + "with the roles: %s";
 
+    public static final String MESSAGE_ADD_CONTACT_WITH_NO_ROLES_TO_EVENT = "The contact: %1s you are adding"
```
Comment (brianchoon) [inline src/main/java/seedu/address/logic/Messages.java:30]: This variable name is very descriptive and avoids ambiguity!

File: src/test/java/seedu/address/logic/commands/event/commands/EventAddAllCommandTest.java [hunk 2]
```diff
@@ -55,15 +63,28 @@ public void execute_correctInputs_success() {
...
     @Test
-    void testEquals_sameObject() {
+    public void testEquals_sameObject() {
         EventAddAllCommand command = new EventAddAllCommand(INDEX_FIRST_EVENT);
         assertTrue(command.equals(command));
     }
 
     @Test
-    void testEquals_differentType() {
+    public void testEquals_differentType() {
```
Comment (brianchoon) [inline src/test/java/seedu/address/logic/commands/event/commands/EventAddAllCommandTest.java:72]: Great test coverage!

**Review by brianchoon — APPROVED** [review]
LGTM!
