### PR TITLE
Change searchmodesearch to throw ParseException on empty input and change success messages

### LINKED ISSUE #196: searchmode search command response to user if no person was added
Currently displays "Added all Persons who fit search parameter" even if no Person was found

### LINKED ISSUE #198: Searchmodesearchcommand allows empty inputs with flags
Inputs like search n/ is currently allowed.

### PR DESCRIPTION
**Pull request by jan-kai1**
Closes #198 , 
Closes #196 
Changes Searchmodesearch to throw a ParseException with invalid command if empty flag inputs are present

Change the user response message to show how many people were added on successful search and No persons found message on  no matching search

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommandTest.java [hunk 1]
```diff
@@ -135,11 +151,30 @@ public void execute_negatedPredicate_success() {
...
 
         SearchModeSearchCommand command = new SearchModeSearchCommand(negatedPredicate);
+        model = new ModelManager(TypicalPersons.getTypicalAddressBook(), getTypicalEventManager(), new UserPrefs());
+        expectedModel = new ModelManager(TypicalPersons.getTypicalAddressBook(), getTypicalEventManager(),
+                new UserPrefs());
+
+        model.updateFilteredPersonList(person -> false);
+        expectedModel.updateFilteredPersonList(negatedPredicate);
+        CommandResult result = command.execute(model, model.getEventManager());
+        //everyone except amy
```
Comment (brianchoon) [inline src/test/java/seedu/address/logic/commands/searchmode/SearchModeSearchCommandTest.java:161]: nit: a small space between `//` and `everyone` will be nice!

File: src/test/java/seedu/address/logic/parser/SearchModeSearchCommandParserTest.java [hunk 2]
```diff
@@ -78,4 +79,46 @@ public void parse_allFieldsSpecified_success() {
...
+        assertParseFailure(parser, " a/", String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                SearchModeSearchCommand.MESSAGE_USAGE));
+    }
+
+    @Test
+    public void parse_telegFlagField_success() {
+        SearchModeSearchCommand expectedCommand = new SearchModeSearchCommand(
+                new TelegramContainsKeywordsPredicate(Collections.singletonList("Amy123")));
+        assertParseSuccess(parser, " t/Amy123", expectedCommand);
+    }
```
Comment (brianchoon) [inline src/test/java/seedu/address/logic/parser/SearchModeSearchCommandParserTest.java:123]: Wonderful test case coverage here! You covered all the cases!

**Review by brianchoon — APPROVED** [review]
LGTM!
