### PR TITLE
Fix searchmode bug

### LINKED ISSUE #272: [PE-D][Tester A] Suggestion: The error message in search mode is a bit misleading
# Current implementation
If all contacts fitting a certain criteria have already been found before, then retrying that search results in the error message "No Contacts found with the search parameter."

For example, this sequence of commands:
`search n/a`
`search n/a`

# Suggestions
A more descriptive error message would be more intuitive to users, such as "No additional contacts found for that search parameter"

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AgentHagu/ped#13

### LINKED ISSUE #281: [PE-D][Tester C] search does not work at all
as can be seen here there does exist a telegram username "teleg". 
The reason for notepad is due to the other cosmetic bug where telegram handles cannot be seen if the length of the name is too long.

however given this input: search t/teleg (the input was copied and pasted from the json file)

there are no results

correction to the above, the entire feature does not work. no results show up no matter what the filter is.
due to the severity of this bug, here is an attached video.

<i><video controls><source src="https://raw.githubusercontent.com/KiKuasaurus/ped/main/files/2f0a452f-252a-4d51-ab68-5ab27d528bf5.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/KiKuasaurus/ped/main/files/2f0a452f-252a-4d51-ab68-5ab27d528bf5.mp4</i>

reason for high is that the feature does not work at all

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: KiKuasaurus/ped#9

### PR DESCRIPTION
**Pull request by cshao02**
Fixes #281
Fixes #272 

Search mode breaks down when a telegram username search is performed on contacts with no telegram username. This is because contacts with no telegram username have null as their telegram username field and calling a method on null leads to java.lang.reflect.invocationtargetexception.

This PR attempts to fix it by first checking if the contact has a telegram username. If the contact does not have a telegram username, then the predicate will immediately return false.

Furthermore, the error message when no contacts are found is made more general to accommodate the case when no contacts are found due to the contacts already existing in search results.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/predicates/TelegramContainsKeywordsPredicate.java [hunk 1]
```diff
@@ -27,6 +27,9 @@ public TelegramContainsKeywordsPredicate(List<String> keywords) {
 
     @Override
     public boolean test(Person person) {
+        if (!person.hasTelegramUsername()) {
```
Comment (jan-kai1) [inline src/main/java/seedu/address/model/person/predicates/TelegramContainsKeywordsPredicate.java:30]: Looks good, solves the issue of checks done on null Telegrams

**Review by jan-kai1 — APPROVED** [review]
Looks good, might have to consider adding similar defensive checks on the other fields to better adhere defensive programming methodology (but shouldn't need to the rest of the fields are mandatory?)
