### PR TITLE
Fix Phone Number Bug

### LINKED ISSUE #249: [PE-D][Tester E] Phone Number Bug
The phone number of a contact does not comply with the standard phone number format in Singapore.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: calebchongsj/ped#2

### PR DESCRIPTION
**Pull request by brianchoon**
## Overview

Previously, we only set a lower bound to the length of the phone number of a Person. We enforced a minimum length of 3. However, there was no upper bound. This PR address the issue.

## Issues Fixed

Closes #249

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -10,9 +10,9 @@
 public class Phone {
 
 
-    public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long.";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+    public static final String MESSAGE_CONSTRAINTS = "Phone numbers should only contain numbers, "
+            + "and it should be between 3 and 17 digits long (both inclusive).";
```
Comment (shardhrv) [inline src/main/java/seedu/address/model/person/Phone.java:14]: Nice clear message
